baseURL = "https://amphibiandisease.org/"
languageCode = "en-us"
title = "Amphibian Disease Portal"
theme = ["futres","kube"]
homepageText = "Amphibian Disease"
publishDir = "docs"


[[menu.main]]
  name = "Query"
  weight = 1
  identifier = "query"
  url = "/query/"

[[menu.main]]
  name = "Data Dashboard"
  weight = 2
  identifier = "dashboard"
  url = "/dashboard/"

[[menu.main]]
  name = "Projects"
  weight = 3
  identifier = "projects"
  url = "/projects/"

[[menu.main]]
  name = "Contribute Data"
  weight = 4
  identifier = "contributing"
  url = "/contributing/"

[[menu.main]]
  name = "About"
  weight = 5
  identifier = "about"
  url = "/about/"
